# Generated by Django 4.2 on 2024-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время')),
                ('ip_src', models.GenericIPAddressField(blank=True, null=True, verbose_name='SRC IP')),
                ('ip_dst', models.GenericIPAddressField(blank=True, null=True, verbose_name='DST IP')),
                ('user', models.CharField(max_length=50, verbose_name='Источник')),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('matching_count', models.IntegerField()),
                ('signals', models.ManyToManyField(to='mainapp.signal')),
            ],
        ),
    ]
