# Generated by Django 4.2 on 2024-01-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-address'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='matching_count',
            field=models.IntegerField(verbose_name='Число сигналов'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='signals',
            field=models.ManyToManyField(to='mainapp.signal', verbose_name='Сигналы'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signal',
            name='message_text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
