# Generated by Django 4.2 on 2024-01-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='message_text',
        ),
        migrations.AlterField(
            model_name='signal',
            name='uid',
            field=models.IntegerField(verbose_name='id Источника'),
        ),
    ]
