# Generated by Django 4.2 on 2024-01-12 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_signal_message_text_alter_signal_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
