# Generated by Django 4.2 on 2024-01-12 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_signal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 3, 35, 10, 399760, tzinfo=datetime.timezone.utc), verbose_name='Дата и время'),
        ),
    ]
