# Generated by Django 4.2 on 2024-01-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_signal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
